import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Toaster } from "@/components/ui/sonner";
import NextAuthProvider from "@/provider/NextAuthProvider";
import ModalProvider from "@/provider/ModalProvider";
import ReactQueryProvider from "@/provider/ReactQueryProvider";

const Font = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "MyBusiness",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Font.className}>
        <ReactQueryProvider>
          <NextAuthProvider>
            {children}
            <Toaster />
            <ModalProvider />
          </NextAuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
